# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [2]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [3]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [4]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [5]:
vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [6]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [8]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [9]:
print(mat)
print(vec)

[[1 2 1]
 [4 5 9]
 [1 8 9]]
[1 2 3]


In [14]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [15]:
mat.dot(vec)

array([ 8, 41, 44])

In [16]:
np.dot(mat,vec)

array([ 8, 41, 44])

In [17]:
mat * vec

array([[ 1,  4,  3],
       [ 4, 10, 27],
       [ 1, 16, 27]])

In [18]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [22]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [23]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.99116049 0.66625594 0.77761528 0.03638963 0.29339723]
 [0.33911027 0.74621514 0.31251092 0.4791461  0.35483595]
 [0.66478365 0.30880531 0.09953722 0.44506926 0.36428569]
 [0.68133116 0.62899402 0.21391532 0.30381956 0.83083085]
 [0.82222651 0.11531624 0.36411134 0.5314824  0.94354631]]

[[-0.56141843  1.91734028  0.4720145  -0.82731453 -0.15911546]
 [ 2.44995449 -1.37418847 -0.69768307  1.79197182  2.11601865]
 [ 0.91644835  0.90208101  0.07408062 -0.55102168 -0.47250492]
 [-0.14959891 -1.35195859 -0.7779174   0.46228998 -0.29341967]
 [-0.55365475  0.8731777  -1.09154142 -0.7785624  -1.13544473]
 [-0.74788678 -0.35133713 -0.29918072 -0.66573593 -1.90367407]
 [ 1.92872069 -0.79790859 -0.08930716 -0.88822307 -1.42284965]
 [-0.29301033  1.50324043 -2.55473052  0.83300203 -0.83593229]
 [ 0.9868667  -0.04980365  1.40407971 -0.58298902 -0.5413325 ]
 [ 0.22578422 -0.45522544  1.66175656 -1.8746602  -0.64540779]]


In [24]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.4925876723922133
1.116676262526061


In [25]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.036389632427645924
2.449954491463566


In [26]:
# break here for next video!

In [27]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[-1.54416973  1.11690219 -0.233633   -0.35594579 -0.82222901 -1.48732726
 -0.75783412  0.07393197 -2.28644462  1.63178019 -0.01599582  0.21023363
  0.06034095  0.47140762 -1.29579691  0.9644468   0.28985137  0.47502727
  0.93669265]
-0.7578341205485174


In [28]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[-0.82222901 -1.48732726 -0.75783412  0.07393197 -2.28644462]


In [29]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[-1.54416973 -0.35594579 -0.75783412  1.63178019  0.06034095]


In [30]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])

[[0.99116049 0.66625594 0.77761528 0.03638963 0.29339723]
 [0.33911027 0.74621514 0.31251092 0.4791461  0.35483595]
 [0.66478365 0.30880531 0.09953722 0.44506926 0.36428569]
 [0.68133116 0.62899402 0.21391532 0.30381956 0.83083085]
 [0.82222651 0.11531624 0.36411134 0.5314824  0.94354631]]
0.31251092323004526
0.31251092323004526


In [31]:
print(rand_mat[0:2,1:3])

[[0.66625594 0.77761528]
 [0.74621514 0.31251092]]


In [40]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[-1.54416973  1.11690219 -0.233633    1.          2.         -1.48732726
 -0.75783412  0.07393197 -2.28644462  1.63178019 -0.01599582  0.21023363
  0.06034095  0.47140762 -1.29579691  0.9644468   0.28985137  0.47502727
  0.93669265]

[-1.54416973  1.11690219 -0.233633    4.          4.         -1.48732726
 -0.75783412  0.07393197 -2.28644462  1.63178019 -0.01599582  0.21023363
  0.06034095  0.47140762 -1.29579691  0.9644468   0.28985137  0.47502727
  0.93669265]

[-1.54416973  1.11690219 -0.233633    1.          2.         -1.48732726
 -0.75783412  0.07393197 -2.28644462  1.63178019 -0.01599582  0.21023363
  0.06034095  0.47140762 -1.29579691  0.9644468   0.28985137  0.47502727
  0.93669265]


In [41]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[3.         3.         3.         0.03638963 0.29339723]
 [3.         3.         3.         0.         0.        ]
 [0.66478365 0.30880531 0.09953722 0.         0.        ]
 [0.68133116 0.62899402 0.21391532 0.30381956 0.83083085]
 [0.82222651 0.11531624 0.36411134 0.5314824  0.94354631]]

[[3.         3.         3.         0.03638963 0.29339723]
 [3.         3.         3.         0.         0.        ]
 [0.66478365 0.30880531 0.09953722 0.         0.        ]
 [0.68133116 0.62899402 0.21391532 0.30381956 0.83083085]
 [0.82222651 0.11531624 0.36411134 0.5314824  0.94354631]]


In [45]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)

[[3. 3. 3.]
 [3. 3. 3.]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [46]:
print(rand_mat)

[[3.         3.         3.         0.03638963 0.29339723]
 [3.         3.         3.         0.         0.        ]
 [0.66478365 0.30880531 0.09953722 0.         0.        ]
 [0.68133116 0.62899402 0.21391532 0.30381956 0.83083085]
 [0.82222651 0.11531624 0.36411134 0.5314824  0.94354631]]


In [47]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)

[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.03638963 0.29339723]
 [3.         3.         3.         0.         0.        ]
 [0.66478365 0.30880531 0.09953722 0.         0.        ]
 [0.68133116 0.62899402 0.21391532 0.30381956 0.83083085]
 [0.82222651 0.11531624 0.36411134 0.5314824  0.94354631]]


In [ ]:
# break here for next video

In [ ]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

In [ ]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

In [ ]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

In [ ]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [ ]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [ ]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

In [ ]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

In [ ]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)